import { Customer, Order, Product, Shop } from '../types';
import { calculateOrderProfit, calculateReturnLoss } from '../utils/calculations';

export const INITIAL_SHOPS: Shop[] = [
  {
    id: 'shop_tahoora',
    owner_id: 'user_default',
    name: 'তহুরা ক্লথিং (Tahoora Clothing)',
    fb_page_name: 'Tahoora Clothing BD',
    fb_page_url: 'https://facebook.com/tahoora.clothing.bd',
    category: 'fashion',
    phone: '01712345678',
    logo_url: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=150&auto=format&fit=crop&q=80',
    default_delivery_inside: 80,
    default_delivery_outside: 130,
    default_packaging_cost: 25,
    default_ad_cost: 110,
    subscription_plan: 'founder',
    subscription_status: 'active',
    subscription_expires_at: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'shop_khati',
    owner_id: 'user_default',
    name: 'খাঁটি অর্গানিক ফুড (Khati Organic)',
    fb_page_name: 'Khati Organic Food BD',
    fb_page_url: 'https://facebook.com/khati.organic.bd',
    category: 'food',
    phone: '01819988776',
    logo_url: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=150&auto=format&fit=crop&q=80',
    default_delivery_inside: 90,
    default_delivery_outside: 140,
    default_packaging_cost: 35,
    default_ad_cost: 130,
    subscription_plan: 'free_trial',
    subscription_status: 'active',
    subscription_expires_at: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod_1',
    shop_id: 'shop_tahoora',
    name: 'কটন কাশ্মীরি পাঞ্জাবি',
    sku: 'PJ-KASH-01',
    variant: 'রয়েল ব্লু / XL',
    selling_price: 1450,
    cost_price: 720,
    stock: 58,
    image_url: 'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=200&auto=format&fit=crop&q=80',
    created_at: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'prod_2',
    shop_id: 'shop_tahoora',
    name: 'প্রিমিয়াম জর্জেট পার্টি গাউন',
    sku: 'GWN-PREM-02',
    variant: 'মেরুন / L',
    selling_price: 2150,
    cost_price: 1100,
    stock: 24,
    image_url: 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=200&auto=format&fit=crop&q=80',
    created_at: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'prod_3',
    shop_id: 'shop_tahoora',
    name: 'টাঙ্গাইল সফট কটন শাড়ি',
    sku: 'SRI-TANG-03',
    variant: 'হলুদ ও লাল পাড়',
    selling_price: 1650,
    cost_price: 850,
    stock: 35,
    image_url: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=200&auto=format&fit=crop&q=80',
    created_at: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'prod_4',
    shop_id: 'shop_tahoora',
    name: 'পিওর সিল্ক ওড়না',
    sku: 'SLK-ORN-04',
    variant: 'কালো / ফ্রি সাইজ',
    selling_price: 550,
    cost_price: 240,
    stock: 80,
    image_url: 'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=200&auto=format&fit=crop&q=80',
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  // Khati products
  {
    id: 'prod_5',
    shop_id: 'shop_khati',
    name: 'সুন্দরবনের খাঁটি প্রাকৃতিক মধু',
    sku: 'HONEY-SUN-01',
    variant: '১ কেজি কাচের জার',
    selling_price: 1250,
    cost_price: 680,
    stock: 40,
    image_url: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=200&auto=format&fit=crop&q=80',
    created_at: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cust_1',
    shop_id: 'shop_tahoora',
    name: 'তানভীর আহমেদ',
    phone: '01712987654',
    district: 'ঢাকা',
    thana: 'মিরপুর ১০',
    full_address: 'বাড়ি ১২, রোড ৪, ব্লক সি, মিরপুর ১০',
    total_orders: 3,
    delivered_orders: 3,
    returned_orders: 0,
    total_sales: 4650,
    estimated_profit: 1720,
    created_at: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'cust_2',
    shop_id: 'shop_tahoora',
    name: 'নুসরাত জাহান রিয়া',
    phone: '01819345678',
    district: 'চট্টগ্রাম',
    thana: 'হালিশহর',
    full_address: 'হাউজ ২১, লেন ৩, কে-ব্লক, হালিশহর হাউজিং',
    total_orders: 2,
    delivered_orders: 2,
    returned_orders: 0,
    total_sales: 3800,
    estimated_profit: 1390,
    created_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'cust_3',
    shop_id: 'shop_tahoora',
    name: 'শরীফুল ইসলাম',
    phone: '01911223344',
    district: 'সিলেট',
    thana: 'জিন্দাবাজার',
    full_address: 'মিতা কমপ্লেক্স ৩য় তলা, জিন্দাবাজার',
    total_orders: 2,
    delivered_orders: 1,
    returned_orders: 1,
    total_sales: 1530,
    estimated_profit: 120, // Reduced due to return
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'cust_4',
    shop_id: 'shop_tahoora',
    name: 'আয়েশা সিদ্দিকা',
    phone: '01622556677',
    district: 'ঢাকা',
    thana: 'উত্তরা',
    full_address: 'সেক্টর ৭, রোড ৯, বাড়ি ১৪, উত্তরা',
    total_orders: 1,
    delivered_orders: 0,
    returned_orders: 0,
    total_sales: 2230,
    estimated_profit: 690,
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord_101',
    shop_id: 'shop_tahoora',
    order_number: 'BP-1001',
    customer_name: 'তানভীর আহমেদ',
    phone: '01712987654',
    district: 'ঢাকা',
    thana: 'মিরপুর ১০',
    full_address: 'বাড়ি ১২, রোড ৪, ব্লক সি, মিরপুর ১০',
    product_name: 'কটন কাশ্মীরি পাঞ্জাবি',
    variant: 'রয়েল ব্লু / XL',
    quantity: 1,
    selling_price: 1450,
    delivery_charge: 80,
    advance_payment: 0,
    payment_method: 'Cash on Delivery',
    product_cost: 720,
    courier_cost: 80,
    packaging_cost: 25,
    ad_cost: 110,
    other_cost: 0,
    return_courier_cost: 0,
    return_loss_amount: 0,
    calculated_profit: 595, // 1530 - (720 + 80 + 25 + 110)
    profit_margin_pct: 38.9,
    status: 'Delivered',
    notes: 'কল দিয়ে ডেলিভারি দিতে হবে। দুপুর ২টার পর।',
    invoice_id: 'INV-1001',
    created_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'ord_102',
    shop_id: 'shop_tahoora',
    order_number: 'BP-1002',
    customer_name: 'নুসরাত জাহান রিয়া',
    phone: '01819345678',
    district: 'চট্টগ্রাম',
    thana: 'হালিশহর',
    full_address: 'হাউজ ২১, লেন ৩, কে-ব্লক, হালিশহর হাউজিং',
    product_name: 'প্রিমিয়াম জর্জেট পার্টি গাউন',
    variant: 'মেরুন / L',
    quantity: 1,
    selling_price: 2150,
    delivery_charge: 130,
    advance_payment: 200,
    payment_method: 'bKash',
    product_cost: 1100,
    courier_cost: 130,
    packaging_cost: 25,
    ad_cost: 110,
    other_cost: 0,
    return_courier_cost: 0,
    return_loss_amount: 0,
    calculated_profit: 915, // 2280 - (1100 + 130 + 25 + 110)
    profit_margin_pct: 40.1,
    status: 'Delivered',
    notes: 'অ্যাডভান্স ২০০ টাকা বিকাশ করা আছে।',
    invoice_id: 'INV-1002',
    created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'ord_103',
    shop_id: 'shop_tahoora',
    order_number: 'BP-1003',
    customer_name: 'শরীফুল ইসলাম',
    phone: '01911223344',
    district: 'সিলেট',
    thana: 'জিন্দাবাজার',
    full_address: 'মিতা কমপ্লেক্স ৩য় তলা, জিন্দাবাজার',
    product_name: 'টাঙ্গাইল সফট কটন শাড়ি',
    variant: 'হলুদ ও লাল পাড়',
    quantity: 1,
    selling_price: 1650,
    delivery_charge: 130,
    advance_payment: 0,
    payment_method: 'Cash on Delivery',
    product_cost: 850,
    courier_cost: 130,
    packaging_cost: 25,
    ad_cost: 110,
    other_cost: 10,
    return_courier_cost: 65,
    return_loss_amount: 340, // 130 (outbound) + 65 (return) + 25 (pack) + 110 (ad) + 10 (other)
    calculated_profit: -340, // Loss on return
    profit_margin_pct: 0,
    status: 'Returned',
    notes: 'গ্রাহক পার্সেল গ্রহণ করেননি। ফোন রিসিভ হয়নি।',
    invoice_id: 'INV-1003',
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'ord_104',
    shop_id: 'shop_tahoora',
    order_number: 'BP-1004',
    customer_name: 'আয়েশা সিদ্দিকা',
    phone: '01622556677',
    district: 'ঢাকা',
    thana: 'উত্তরা',
    full_address: 'সেক্টর ৭, রোড ৯, বাড়ি ১৪, উত্তরা',
    product_name: 'প্রিমিয়াম জর্জেট পার্টি গাউন',
    variant: 'মেরুন / L',
    quantity: 1,
    selling_price: 2150,
    delivery_charge: 80,
    advance_payment: 0,
    payment_method: 'Cash on Delivery',
    product_cost: 1100,
    courier_cost: 80,
    packaging_cost: 25,
    ad_cost: 110,
    other_cost: 0,
    return_courier_cost: 0,
    return_loss_amount: 0,
    calculated_profit: 915,
    profit_margin_pct: 41.0,
    status: 'Shipped',
    notes: 'স্টেডফাস্ট কুরিয়ার ট্র্যাকিং #SF-889921',
    invoice_id: 'INV-1004',
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ord_105',
    shop_id: 'shop_tahoora',
    order_number: 'BP-1005',
    customer_name: 'ফারহানা মিলি',
    phone: '01799112233',
    district: 'ঢাকা',
    thana: 'ধানমন্ডি',
    full_address: 'রোড ৮/এ, বাড়ি ৩৭, ধানমন্ডি',
    product_name: 'কটন কাশ্মীরি পাঞ্জাবি',
    variant: 'রয়েল ব্লু / XL',
    quantity: 2,
    selling_price: 1450,
    delivery_charge: 80,
    advance_payment: 500,
    payment_method: 'bKash',
    product_cost: 720,
    courier_cost: 80,
    packaging_cost: 30,
    ad_cost: 110,
    other_cost: 0,
    return_courier_cost: 0,
    return_loss_amount: 0,
    calculated_profit: 1320, // 2980 - (1440 + 80 + 30 + 110)
    profit_margin_pct: 44.3,
    status: 'New',
    notes: 'AI মেসেঞ্জার থেকে তৈরি ড্রাফট। বিকাশ ট্রানজ্যাকশন ভেরিফাইড।',
    invoice_id: 'INV-1005',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
