import { SubscriptionPlan } from '../types';

export const SUBSCRIPTION_PLANS: SubscriptionPlan[] = [
  {
    id: 'free_trial',
    name: 'Free Trial',
    nameBn: 'ফ্রি ট্রায়াল',
    priceBDT: 0,
    durationLabel: '১৪ দিন সম্পূর্ণ ফ্রি',
    durationDays: 14,
    monthlyAILimit: 50,
    features: [
      '৫০টি AI মেসেঞ্জার অর্ডার ক্যাপচার',
      'ম্যানুয়াল আনলিমিটেড অর্ডার ট্র্যাকিং',
      'রিয়েলটাইম নিট লাভ ও রিটার্ন লস হিসাব',
      '১ ক্লিকে বাংলা PDF ইনভয়েস তৈরি',
      'কাস্টমার হিস্ট্রি ও কুরিয়ার ট্র্যাকিং নোট',
    ],
  },
  {
    id: 'founder',
    name: 'Founder',
    nameBn: 'ফাউন্ডার মেম্বারশিপ',
    priceBDT: 99,
    durationLabel: '৬০ দিনের জন্য মাত্র ৯৯ টাকা',
    durationDays: 60,
    monthlyAILimit: 300,
    badge: 'সেরা অফার 🔥',
    features: [
      '৩০০টি AI মেসেঞ্জার অর্ডার ক্যাপচার',
      '৬০ দিন সম্পূর্ণ আনলিমিটেড সার্ভিস',
      'ডেলিভারি ও রিটার্ন লস অডিট রিপোর্ট',
      'কাস্টমার ও প্রোডাক্ট CSV এক্সপোর্ট/ইমপোর্ট',
      'অগ্রাধিকার ভিআইপি সাপোর্ট',
    ],
  },
  {
    id: 'standard',
    name: 'Standard',
    nameBn: 'স্ট্যান্ডার্ড প্যাক',
    priceBDT: 249,
    durationLabel: 'প্রতি মাসে ২৪৯ টাকা',
    durationDays: 30,
    monthlyAILimit: 800,
    features: [
      '৮০০টি AI মেসেঞ্জার অর্ডার ক্যাপচার',
      'আনলিমিটেড প্রোডাক্ট ও ইনভেন্টরি ট্র্যাকিং',
      '৭ দিনের সেলস ও নিট প্রফিট গ্রাফ',
      'উন্নত কাস্টমার রিটার্ন রেট অ্যানালাইসিস',
      'কাস্টম শপ লোগো সহ বাংলা ইনভয়েস',
    ],
  },
  {
    id: 'growth',
    name: 'Growth',
    nameBn: 'গ্রোথ প্রো প্যাক',
    priceBDT: 499,
    durationLabel: 'প্রতি মাসে ৪৯৯ টাকা',
    durationDays: 30,
    monthlyAILimit: 3000,
    badge: 'বড় পেজের জন্য',
    features: [
      'আনলিমিটেড AI মেসেঞ্জার অর্ডার ক্যাপচার',
      'মাল্টি-শপ সাপোর্ট (একাধিক পেজ ম্যানেজ)',
      'অ্যাড কস্ট ও আরওআই (ROI) অ্যানালিটিক্স',
      'ডেডিকেটেড হোয়াটসঅ্যাপ হেল্পডেস্ক',
      'সকল প্রিমিয়াম ফিচার আনলক',
    ],
  },
];
